### ISSUE TITLE
[Enhancement] The ability to tag posts

### ISSUE THREAD

**Issue by Ki-er** [muenzpraeger/eleventy-chirpy-blog-template#176]
# What is missing from the application? Please describe
The ability to tag posts with categories would be neat, like `docker` or `personal`

## Describe the solution you'd like
```
---
layout: post
title: "How to install Docker and Docker Compose"
date: 2022-05-28
categories: docker
tags: docker docker-compose
---
```

## Describe alternatives you've considered
The original jekyll version supports this.

## Additional context
![image](https://user-images.githubusercontent.com/32241933/187467826-b2fd789a-9be4-4172-a910-3c592c8c2a2c.png)
![image](https://user-images.githubusercontent.com/32241933/187467860-e72ed370-c082-4f13-ae56-906f3f185e36.png)
![image](https://user-images.githubusercontent.com/32241933/187467935-7d78ede5-2b4c-4d51-a752-af8456de1f65.png)

**Comment by cyril-sabourault** [comment]
Hi! Not the owner, but I'm pretty new to 11ty and found myself doing pretty much this yesterday. Hope this can help you.

`tags` in the frontmatter are used to create collections of posts.  
In this template, all posts under the "content/posts/" folder will be implicitly tagged "posts" using "[directory data files](https://www.11ty.dev/docs/data-template-dir/)" from the data in "content/posts/posts.json".

The first thing you want to do is enabling [data cascade](https://www.11ty.dev/docs/data-cascade/) in Eleventy, this will allow you set tags from different locations and not just overwrite all values with your file frontmatter.
Add this line somewhere in .eleventy.js between the `module.exports` brackets:
```js
eleventyConfig.setDataDeepMerge(true);
```

Now in order to regroup posts by topics I added a second key `labels:` to my frontmatter
```yaml
# content/posts/post1.md
---
title: Post 1 Title
date: 2022-08-25
image: /assets/images/2022/post1/header.jpg
labels:
    - python
    - docker
    - …
---
```

You can then create a template "labels.njk" to style how you want to display labels

```html
<!-- content/_includes/labels.njk -->
<span class="flex flex-grow flex-row flex-wrap content-end justify-start items-center">
    <svg><!-- svg for the 'label' icon --></svg>

    {% for label in labels %}
    <span class="label px-3 m-1">{{ label }}</span>
    {% endfor%}
</span> 
```

Include this template in the "post.njk" layout or anywhere else on your site.  
I chose to list labels at the top of each post, next to the date and reading time info, and also in the archive section

```html
<!-- content/_includes/post.njk -->
<div class="mb-12 flex text-sm font-light dark:font-extralight">
    <div class="flex">
        <svg></svg>
        {{ date | readableDate }}
    </div>
    <div class="flex readingtime" data-words="{{ content | striptags | wordcount | formatWords }} words">
        <svg></svg>
        {{ content | striptags | wordcount | readingTime }}
        <span></span>
    </div>
    {% include "labels.njk" %}
</div>
```

This will get you something like that:
![image](https://user-images.githubusercontent.com/11644508/187871364-e78ed12d-5565-4a96-af19-846fea6cc30e.png)


I suggest you check the pull requests where I introduced labels in my repo: [Improve labels template #90](https://github.com/Limezest/blog.sabourau.lt/pull/90), it also contains some code to randomly assign colors to labels :)

For now you can't click on a label to filter posts but I'll work on it next!

**Comment by cyril-sabourault** [comment]
I got filtering to work using this trick:


Clicking on a label redirects you to the archive page with an # anchor: clicking on [docker] takes you to "…/archive/#docker".  

I updated the archive template to include a 'data-' attribute with the list of labels, and added a JS script to only show list items that include the anchor value if set.

Details in my [pull request](https://github.com/Limezest/blog.sabourau.lt/pull/91/files) if you want to see

**Comment by Ki-er** [comment]
Thanks @Limezest, Ill close this issue with your solutions below!

I swapped to Hugo for the range of themes so Im not using this theme anymore.
